(() => {
  const F=FRAMEWORK;
  const statusOk=(r)=>["SUBMITTED","UNDER REVIEW","QA APPROVED","FINALIZED"].includes(r.status);
  function reportData(){ const db=P10354.load(); const reports=Object.values(db.reports); const findings=reports.flatMap(r=>(r.findings||[]).map(f=>({r,f,s:P10354.school(r.schoolId)}))); const schools=P10354.schoolsInScope().length; const submitted=reports.filter(statusOk).length; const high=findings.filter(x=>["HIGH","CRITICAL"].includes(x.f.severity||x.f.priority)).length; const open=findings.filter(x=>x.f.status!=="CLOSED").length; return {db,reports,findings,schools,submitted,high,open}; }
  function render(){ const host=UI.$("#executive-report"); UI.reset(); const d=reportData(); const pct=d.schools?Math.round(d.submitted/d.schools*100):0;
    const regions=F.regions.filter(r=>r.active).map(r=>{const ss=P10354.schools.filter(s=>s.region.toUpperCase()===r.id);const rr=ss.map(s=>d.db.reports[s.id]).filter(Boolean);const sub=rr.filter(statusOk).length;const fs=rr.flatMap(x=>x.findings||[]);return {r,schools:ss.length,submitted:sub,pct:ss.length?Math.round(sub/ss.length*100):0,findings:fs.length,open:fs.filter(f=>f.status!=="CLOSED").length};});
    host.innerHTML=`<div class="report-header"><img src="assets/reet-logo.png" alt="REET – Collaborative. Sustainable. Transformative."><div class="report-meta"><span class="project-tag">P10354</span><div class="help">Generated ${new Date().toLocaleString()}</div></div></div><div class="heading"><div><h1>Executive Management Report</h1><p>${UI.esc(F.meta.title)} · ${UI.esc(F.meta.assessor)}</p></div><div class="actions"><button id="print" class="btn large">Print / Save as PDF</button><a class="btn secondary" href="dashboard.html">Back</a></div></div><section class="card pad"><h2>Executive Summary</h2><p>Field assessment reporting is ${pct}% complete, with ${d.submitted} of ${d.schools} schools submitted. There are ${d.open} open actions and ${d.high} high or critical findings requiring attention.</p></section><section class="grid"><article class="card metric green"><small>Completion</small><b>${pct}%</b></article><article class="card metric"><small>Schools submitted</small><b>${d.submitted}/${d.schools}</b></article><article class="card metric amber"><small>Open actions</small><b>${d.open}</b></article><article class="card metric ${d.high?"red":"green"}"><small>High / critical findings</small><b>${d.high}</b></article></section><section class="card"><div class="pad"><h2>Regional Results</h2></div><div class="tablewrap"><table><thead><tr><th>Region</th><th>Schools</th><th>Submitted</th><th>Completion</th><th>Findings</th><th>Open actions</th></tr></thead><tbody>${regions.map(x=>`<tr><td><b>${UI.esc(x.r.name)}</b></td><td>${x.schools}</td><td>${x.submitted}</td><td>${x.pct}%</td><td>${x.findings}</td><td>${x.open}</td></tr>`).join("")}</tbody></table></div></section><section class="card"><div class="pad"><h2>Key Findings and Actions</h2></div><div class="tablewrap"><table><thead><tr><th>School</th><th>Finding</th><th>Priority</th><th>Recommendation</th><th>Owner</th><th>Status</th></tr></thead><tbody>${d.findings.slice(0,25).map(x=>`<tr><td>${UI.esc(x.s?.name||x.r.schoolId)}</td><td>${UI.esc(x.f.finding||"—")}</td><td>${UI.pill(x.f.severity||x.f.priority||"—")}</td><td>${UI.esc(x.f.recommendation||"—")}</td><td>${UI.esc(x.f.owner||"—")}</td><td>${UI.pill(x.f.status||"OPEN")}</td></tr>`).join("")||`<tr><td colspan="6" class="empty">No findings recorded.</td></tr>`}</tbody></table></div></section><section class="card pad"><h2>Report Notes</h2><p>This report is generated directly from records saved in the system. Final conclusions remain subject to the Team Leader review and approval workflow.</p></section>`; document.getElementById("print").onclick=()=>window.print(); }
  (async () => { if (!(await UI.gateAuth())) return; UI.chrome(); render(); })();
})();
